Proposed extensions in order to incorporate storage of ADCP data in s…
ices-publications/SONAR-netCDF4 pull request #39
Opened 2021-02-04 10:02 UTC by SverreBerg

…ub groups.

2021-02-08 14:40 UTC, lberger29 requested changes
Correlation, Error_velocity and quality indicator would benefit with a more precise definition.

Netcdf files can be very large since current_velocity is given in three different coordinate systems (beam, vessel and geographical) and with and without averaging. Current velocities in beam and vessel coordinate system could be optionnal.

2021-02-08 14:40 UTC, lberger29 commented on docs/tableMean_current_sub_group.adoc
> +
This should be defined in ADCP_sub_group  as it is used first for ADCP_sub_group before averaging?

2021-02-09 10:42 UTC, cyrilleponcelet requested changes

2021-02-09 10:42 UTC, cyrilleponcelet commented on .vs/ProjectSettings.json
> +{
You should remove all .vs related code from you commit.

2021-02-09 10:42 UTC, cyrilleponcelet commented on .vs/VSWorkspaceState.json
> +{
You should remove all .vs related code from you commit.

2021-02-09 10:42 UTC, cyrilleponcelet commented on docs/tableSonar.adoc
>   2+|{var}float(*) angle_t |Variable length vector used to store ragged arrays of split-aperture angles. Data type can varied to suit data storage needs.
Type added for ADCP and used in ADCP subgroups only should be defined in ADCP subgroups

2021-02-09 10:42 UTC, cyrilleponcelet commented on docs/tableBeamGroup1.adoc
> +e|Subgroups | |
This should be subgroup description, it has no long_name

Something like this

|Subgroups | |
 |{var}ADCP |O | Subgroup containing ADCP calculated current velocities data.

2021-02-09 10:42 UTC, cyrilleponcelet commented on docs/tableADCP_sub_group.adoc
> +  3+|{attr}:long_name = "Sonar/Beam_group1/ADCP/Mean_current"
This should be subgroup description 

Something like this

|Subgroups | |
 |{var}Mean_current |O | Subgroup containing calculated averaged current velocities data.

2021-02-09 10:42 UTC, cyrilleponcelet commented on docs/crr341.adoc
> +The netCDF4 group name is /ADCP.
The netCDF4 group name is ADCP and is a subgroup of /Sonar/Beam_group

2021-02-09 10:42 UTC, cyrilleponcelet commented on docs/crr341.adoc
> +The netCDF4 group name is /ADCP/Mean-current.
The netCDF4 group name is Mean-current and is a subgroup of ADCP group

2021-04-08 16:07 UTC, cyrilleponcelet commented
Everythings seems fine to me, @gavinmacaulay @lberger29 @nilsolav  can we merge this pull request ?

2021-04-09 00:51 UTC, merged